runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /img/(.+)
  static_files: img/\1  
  upload: img/(.*)     
  secure: always

- url: /style/(.+)
  static_files: style/\1  
  upload: style/(.*)  
  secure: always

- url: /js/(.+)
  static_files: js/\1  
  upload: js/(.*)   
  secure: always
